# Generated by Django 4.1.3 on 2022-11-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='nickname',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
